export const CHANGE_THEME = 'CHANGE_THEME';

export const CHANGE_MODE = 'CHANGE_MODE';

export const CHANGE_NETINFO = 'CHANGE_NETINFO';
export const CHANGE_IF_LOAD_IMG_WHIYOUT_WIFI = 'CHANGE_IF_LOAD_IMG_WHIYOUT_WIFI';